package ignat.malko.model.enums;

public enum RequestType {
    LOGIN, CREATE_ACCOUNT, GET_USER_ACCOUNTS, CLOSE_ACCOUNT, GET_USER_TRANSACTIONS, TRANSFER_MONEY_TO_SAVINGS, TRANSFER_MONEY_BY_NUMBER, TRANSFER_MONEY_BY_ACCOUNT, UPDATE_USER, GET_ALL_ACCOUNTS, UPDATE_ACCOUNT_STATUS, REMOVE_ACCOUNT, GET_ALL_INTEREST_RATES, UPDATE_INTEREST_RATE, GET_ALL_USERS, DELETE_USER, GET_ALL_TRANSACTIONS, ROLLBACK_TRANSACTION, REGISTER
}
